In [185]:
import numpy as np
import itertools as iter
import pandas as pd
import sklearn.metrics as sklm

In [3]:
from pcsPy import *

In [182]:
name = []
prime = []
for n in range(1,12+1):
    # generate all possible combinations of n integers
    a = np.asarray(list(iter.combinations(range(12),n)))
    # put all pcs in prime form
    s = []
    for i in range(a.shape[0]):
        p = PCSet(a[i,:])
        s.append(p.primeForm()[:])

    s = np.asarray(s)
    # eliminate duplicates
    s = np.unique(s,axis=0)
    # calculate interval vectors and assign names
    v = []
    for i in range(s.shape[0]):
        p = PCSet(s[i,:])
        v.append(p.intervalVector())
        name.append(str(n)+'-'+str(i+1))
        prime.append(np.array2string(s[i,:],separator='').replace(" ",""))

    v = np.asarray(v)
    s = np.asarray(s)
    
    if n == 1: 
        vector=v
    else:
        vector = np.vstack((vector,v))

# find pc sets in Z relation
u, indeces = np.unique(vector, return_inverse=True,axis=0)
ZrelT = []
for n in range(u.shape[0]):
    if np.array(np.where(indeces == n)).shape[1] != 1:
        indx = np.array(np.where(indeces == n))[0]
        Zrel = []
        for m in range(indx.shape[0]):
            name[indx[m]] = name[indx[m]]+'Z'
            Zrel.append(name[indx[m]])
        ZrelT.append(Zrel)

name = np.asarray(name)

In [251]:
#for n in range(len(name)):
#    print(name[n],prime[n],np.array2string(vector[n,:],separator='').replace(" ",""))

In [252]:
#ZrelT

In [187]:
df = pd.DataFrame(name,columns=['name'])

In [193]:
df.to_csv('nodes.csv')

In [420]:
N = vector.shape[0]
dist = np.zeros((int((N**2-N)/2+N),3))
n = 0
for i in range(N):
    for j in range(i,N):
        pair = sklm.pairwise.paired_euclidean_distances(vector[i].reshape(1, -1),vector[j].reshape(1, -1))
        if pair <= 3.0 and pair != 0:
            dist[n,0] = i
            dist[n,1] = j
            dist[n,2] = sklm.pairwise.paired_euclidean_distances(vector[i].reshape(1, -1),vector[j].reshape(1, -1))
            n += 1
print(n-1)

4680


In [421]:
dist = dist[:4680]

In [422]:
dist.shape

(4680, 3)

In [423]:
dist[63]

array([ 1.        , 33.        ,  2.23606798])

In [424]:
df2 = pd.DataFrame(dist,columns=['Sources','Targets','Distance'])

In [425]:
df2.style.format({
    'i': '{:,.0f}'.format,
    'j': '{:,.0f}'.format,
    'distance': '{:,.8f}'.format,
})

In [426]:
df2.to_csv('edges.csv')

In [391]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [392]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [393]:
a= np.delete(a,2,0)

In [394]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [406]:
a[2]

IndexError: index 2 is out of bounds for axis 0 with size 2